
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author akash
 */
public class question2 extends javax.swing.JFrame {

    /**
     * Creates new form question2
     */
    public question2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        question_panel = new javax.swing.JPanel();
        ques3id = new javax.swing.JLabel();
        opt3_1 = new javax.swing.JRadioButton();
        opt3_2 = new javax.swing.JRadioButton();
        opt3_3 = new javax.swing.JRadioButton();
        opt3_4 = new javax.swing.JRadioButton();
        ques3 = new javax.swing.JLabel();
        ques4id = new javax.swing.JLabel();
        ques4 = new javax.swing.JLabel();
        opt4_1 = new javax.swing.JRadioButton();
        opt4_2 = new javax.swing.JRadioButton();
        opt4_3 = new javax.swing.JRadioButton();
        opt4_4 = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ques3id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ques3id.setText("Ques3");

        buttonGroup1.add(opt3_1);
        opt3_1.setText("Chennai");
        opt3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opt3_2);
        opt3_2.setText("Delhi");

        buttonGroup1.add(opt3_3);
        opt3_3.setText("Mumbai");

        buttonGroup1.add(opt3_4);
        opt3_4.setText("Bangalore");
        opt3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3_4ActionPerformed(evt);
            }
        });

        ques3.setText("What is the capital of Karnataka?");

        ques4id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ques4id.setText("Ques4");

        ques4.setText("What is the capital of Maharastra?");

        buttonGroup2.add(opt4_1);
        opt4_1.setText("Chennai");
        opt4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(opt4_2);
        opt4_2.setText("Delhi");
        opt4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(opt4_3);
        opt4_3.setText("Mumbai");
        opt4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4_3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(opt4_4);
        opt4_4.setText("Dehradun");

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout question_panelLayout = new javax.swing.GroupLayout(question_panel);
        question_panel.setLayout(question_panelLayout);
        question_panelLayout.setHorizontalGroup(
            question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(question_panelLayout.createSequentialGroup()
                        .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(question_panelLayout.createSequentialGroup()
                                .addComponent(ques3id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(question_panelLayout.createSequentialGroup()
                                        .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(opt3_1)
                                            .addComponent(opt3_3))
                                        .addGap(28, 28, 28)
                                        .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(opt3_2)
                                            .addComponent(opt3_4)))
                                    .addComponent(ques3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(question_panelLayout.createSequentialGroup()
                                .addComponent(ques4id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ques4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(question_panelLayout.createSequentialGroup()
                                        .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(opt4_1)
                                            .addComponent(opt4_3))
                                        .addGap(26, 26, 26)
                                        .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(opt4_2)
                                            .addComponent(opt4_4))))))
                        .addContainerGap(163, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, question_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submit)
                        .addGap(30, 30, 30))))
        );
        question_panelLayout.setVerticalGroup(
            question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ques3id)
                    .addComponent(ques3))
                .addGap(18, 18, 18)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt3_1)
                    .addComponent(opt3_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt3_3)
                    .addComponent(opt3_4))
                .addGap(38, 38, 38)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ques4)
                    .addComponent(ques4id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opt4_2)
                    .addComponent(opt4_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt4_3)
                    .addComponent(opt4_4))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(question_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(question_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt3_1ActionPerformed

    private void opt3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt3_4ActionPerformed

    private void opt4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt4_1ActionPerformed

    private void opt4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt4_2ActionPerformed

    private void opt4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt4_3ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
         if(opt3_4.isSelected())
            Q.c++;
        else
            Q.w++;
          if(opt4_3.isSelected())
            Q.c++;
        else
            Q.w++;
          
        int score = Q.c*3;
        
          try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/online_examination","root","root");
            Statement s= c.createStatement();
            int h = s.executeUpdate("insert into response values('"+Q.std_id+"','"+Q.c+"','"+Q.w+"','"+score+"')");
                if(h>0){
                     javax.swing.JOptionPane.showMessageDialog(this, "Thanks for taking the exam.\nYour score is "+score);
                     System.exit(0);
                }else{
                     javax.swing.JOptionPane.showMessageDialog(this, "There was an error recording your scores, please contact the administrator immediately.");
                }
                
                
           
        } catch(Exception e)
        {
javax.swing.JOptionPane.showMessageDialog(this, "Error;" + e);
        }
          
          
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton opt3_1;
    private javax.swing.JRadioButton opt3_2;
    private javax.swing.JRadioButton opt3_3;
    private javax.swing.JRadioButton opt3_4;
    private javax.swing.JRadioButton opt4_1;
    private javax.swing.JRadioButton opt4_2;
    private javax.swing.JRadioButton opt4_3;
    private javax.swing.JRadioButton opt4_4;
    private javax.swing.JLabel ques3;
    private javax.swing.JLabel ques3id;
    private javax.swing.JLabel ques4;
    private javax.swing.JLabel ques4id;
    private javax.swing.JPanel question_panel;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
