/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author akash
 */
public class questions extends javax.swing.JFrame {

    /**
     * Creates new form questions
     */
    public questions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        question_panel = new javax.swing.JPanel();
        ques1id = new javax.swing.JLabel();
        opt1_1 = new javax.swing.JRadioButton();
        opt1_2 = new javax.swing.JRadioButton();
        opt1_3 = new javax.swing.JRadioButton();
        opt1_4 = new javax.swing.JRadioButton();
        ques1 = new javax.swing.JLabel();
        ques2id2 = new javax.swing.JLabel();
        ques2 = new javax.swing.JLabel();
        opt2_1 = new javax.swing.JRadioButton();
        opt2_2 = new javax.swing.JRadioButton();
        opt2_3 = new javax.swing.JRadioButton();
        opt2_4 = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ques1id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ques1id.setText("Ques1");

        buttonGroup1.add(opt1_1);
        opt1_1.setText("Chennai");
        opt1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1_1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opt1_2);
        opt1_2.setText("Delhi");

        buttonGroup1.add(opt1_3);
        opt1_3.setText("Mumbai");
        opt1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1_3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opt1_4);
        opt1_4.setText("Dehradun");
        opt1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1_4ActionPerformed(evt);
            }
        });

        ques1.setText("What is the capital of Tamil Nadu?");

        ques2id2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ques2id2.setText("Ques2");

        ques2.setText("What is the capital of Uttarakhand?");

        buttonGroup2.add(opt2_1);
        opt2_1.setText("Chennai");
        opt2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(opt2_2);
        opt2_2.setText("Delhi");
        opt2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2_2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(opt2_3);
        opt2_3.setText("Mumbai");

        buttonGroup2.add(opt2_4);
        opt2_4.setText("Dehradun");

        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout question_panelLayout = new javax.swing.GroupLayout(question_panel);
        question_panel.setLayout(question_panelLayout);
        question_panelLayout.setHorizontalGroup(
            question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(question_panelLayout.createSequentialGroup()
                        .addComponent(ques1id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(question_panelLayout.createSequentialGroup()
                                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opt1_1)
                                    .addComponent(opt1_3))
                                .addGap(28, 28, 28)
                                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opt1_2)
                                    .addComponent(opt1_4)))
                            .addComponent(ques1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(question_panelLayout.createSequentialGroup()
                        .addComponent(ques2id2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(question_panelLayout.createSequentialGroup()
                                .addComponent(opt2_1)
                                .addGap(26, 26, 26)
                                .addComponent(opt2_2))
                            .addGroup(question_panelLayout.createSequentialGroup()
                                .addComponent(opt2_3)
                                .addGap(30, 30, 30)
                                .addComponent(opt2_4))
                            .addComponent(ques2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, question_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next)
                .addContainerGap())
        );
        question_panelLayout.setVerticalGroup(
            question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ques1id)
                    .addComponent(ques1))
                .addGap(18, 18, 18)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt1_1)
                    .addComponent(opt1_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt1_3)
                    .addComponent(opt1_4))
                .addGap(38, 38, 38)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ques2)
                    .addComponent(ques2id2))
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(question_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opt2_2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(question_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(opt2_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opt2_3)
                            .addComponent(opt2_4))
                        .addGap(26, 26, 26)
                        .addComponent(next)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(question_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(question_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt1_1ActionPerformed

    private void opt2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt2_1ActionPerformed

    private void opt2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt2_2ActionPerformed

    private void opt1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt1_4ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        
        if(opt1_1.isSelected())
            Q.c++;
        else
            Q.w++;
         if(opt2_4.isSelected())
            Q.c++;
        else
            Q.w++;
                
         question2 qq = new question2();
        qq.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nextActionPerformed

    private void opt1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt1_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton next;
    private javax.swing.JRadioButton opt1_1;
    private javax.swing.JRadioButton opt1_2;
    private javax.swing.JRadioButton opt1_3;
    private javax.swing.JRadioButton opt1_4;
    private javax.swing.JRadioButton opt2_1;
    private javax.swing.JRadioButton opt2_2;
    private javax.swing.JRadioButton opt2_3;
    private javax.swing.JRadioButton opt2_4;
    private javax.swing.JLabel ques1;
    private javax.swing.JLabel ques1id;
    private javax.swing.JLabel ques2;
    private javax.swing.JLabel ques2id2;
    private javax.swing.JPanel question_panel;
    // End of variables declaration//GEN-END:variables
}
